name: First Workflow

on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              run: |
                echo 'Hello World 1'
                echo 'Hello World 2'